neogcamp/platform-93by4

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom_issue.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
Changes
* Add ISSUE Templates for bug report, custom issue and feature request
* Add Pull Request Template for proper PR documentation
Feel free to drop your suggestions or additions to the template.
Thanks
> Add Issue Template and Pull Request Template 

- client/src/context/AuthContext.tsx
- src/routes/AuthRoutes.ts
Fixed a small bug where context was not getting set through setState
> fix : applied small fix for setting context state

- CODE_OF_CONDUCT.md
This PR adds code of conduct file to the project.
- No major change.
> add CODE_OF_CONDUCT.md file

- client/public/svgs/circleCheck.svg
- client/src/components/Card/Card.tsx
- client/src/components/LockIcon/LockIcon.tsx
- client/src/data/staticData/mark15.ts
- client/src/pages/auth/email-verification/[verificationToken].tsx
- client/src/pages/auth/forgot-password/[passwordResetToken].tsx
- client/src/pages/submission/checklist.tsx
- client/yarn.lock
> check icon fix

- client/src/components/Footer/Footer.tsx
- client/src/pages/index.tsx
> Fix: Next Routing + Navlinks

- client/public/svgs/chevDown.svg
- client/src/components/Card/Card.tsx
- client/src/components/CardText/CardText.tsx
- client/src/components/CheckList/CheckList.tsx
- client/src/components/LockIcon/LockIcon.tsx
- yarn.lock
- mark15 layout bug fix
- none
> Final portfolio submission

- client/public/svgs/chevDown.svg
- client/src/components/Card/Card.tsx
- client/src/components/CardText/CardText.tsx
- client/src/components/LockIcon/LockIcon.tsx
- client/src/data/staticData/mark15.ts
- client/src/pages/auth/login.tsx
- client/src/pages/auth/signup.tsx
- client/src/pages/submission/index.tsx
- Now users have to do all mark15 checks before going to the submission page.
- `mark15` data structure changes to fix mark15 checklist-related bugs.
- none
> Submission fixes

- client/src/pages/auth/forgot-password/index.tsx
- client/src/pages/submission/index.tsx
- minor fixes for the mark15 checklist and the submission portal
- none
> fix: mark15 checklist redirection issue

- client/src/data/strings/questions.tsx
- client/src/pages/submission/checklist.tsx
- client/src/pages/submission/questions.tsx
Adds links to mark15 submission page and fixes minor bugs at multiple pages.
- no major changes
- Please affirm to the links put here.
> Fix minor bugs and add link to mark15 question submission page

- client/src/pages/submission/index.tsx
-removed unwanted lines causing error
- None
- Issue #90 
- Pull Request #
> bug: fix submission page

- .github/workflows/main_neog-admissions.yml
Added workflow to install client-side npm packages
> Fixes client npm install

- .github/workflows/main_neog-admissions.yml
> small fix in yaml

- .github/workflows/main_neog-admissions.yml
- .gitignore
- package.json
Changed build command so it would not run the node js API in workflow itself.
Changed it to match wyzr's
> tweaks to start command

- client/package.json
- package.json
Removed part where nextjs app was getting exported after github action because of chained commands ..
- Delete node_modules from frontend artifact
> removed -> Duplicate compilation of nextjs

- .gitignore
- client/src/pages/resubmission/index.tsx
- client/src/pages/submission/index.tsx
- client/src/services/axiosService.ts
- src/controllers/AuthController.ts
This adds one more env file on the client-side. 
For developing locally, please create a .env.local in the client folder with the following variable if you are working on a production branch. 
-> NEXT_PUBLIC_API_ENDPOINT='https://neog-admissions.azurewebsites.net/api'
and for the backend pls add this variable 
-> FRONTEND_URL='https://neog-admissions.azurewebsites.net'
Fixed an issue where email origin was localhost instead of production URL
Fixed an issue where various requests to the backend were failing 
Add support for requests to production URL
> Fix: Removed references to localhost

- src/models/Portfolio.ts
- src/models/Reviewer.ts
- src/routes/AdminRoutes.ts
```ts
export interface IUser {
email: string
isVerified: boolean
firstName: string
lastName: string
password: string
verificationToken: string | undefined
passwordResetToken: string | undefined
passwordResetTokenExpire: Date | undefined
verificationTokenExpiresIn: Date | undefined
getPasswordResetToken: () => Promise<string>
getEmailVerificationToken: () => Promise<string>
matchPasswords: (password: string) => Promise<boolean>
portfolioUrl: PopulatedDoc<IPortfolioUrl & Document>
}
```
```ts
const userSchema = new Schema<IUser, Model<IUser>, IUser>(
{
firstName: {
type: String,
required: true,
trim: true,
},
lastName: {
type: String,
required: true,
trim: true,
},
email: {
type: String,
required: true,
unique: true,
lowercase: true,
},
password: {
type: String,
required: true,
minlength: …
```
> Fix: Schema for the portfolioUrl, Reviewer

- client/src/components/BreadCrumbs/BreadCrumbs.tsx
- client/src/pages/_app.tsx
- Solved using [this](https://chakra-ui.com/docs/navigation/breadcrumb#usage-with-routing-library) doc reference
- Please check if it working properly on branch. Then we can merge it to main
> fix breadcrumb link page reloading

- client/src/components/Card/Card.tsx
- client/src/components/StepCard/StepCard.tsx
- client/src/data/staticData/mark15.ts
1. Copy Fix
2. Status Card Reponsiveness
3. Made Text Card Clickable
> fix: responsive & copy

- client/src/components/BgPattern/BgPattern.tsx
- client/src/pages/auth/login.tsx
- client/src/pages/auth/signup.tsx
1. fixed-layout shifts
2. changed the image to CSS pattern to improve performance
- Issue #140
> fix: login layout

- client/src/pages/resubmission/index.tsx
- client/src/pages/submission/index.tsx
Reverts neogcamp/platform-93by4#181
> Revert "Different tweets"

- client/src/pages/index.tsx
- Add: Alert Box regarding deadline on the home page
> Add: Deadline Alert

- client/src/components/Review/NeedsRevisionPanel.tsx
- client/src/components/Review/PortfolioPanel.tsx
- client/src/pages/admin/dashboard/index.tsx
Fixes bugs in review sys UI,
removed link to portfolios. Instead its rendered in plain text to avoid going to wrong URLs 
fixed state vars not getting updated. 
Applied min 20 words validation on needs review comment
> fixed bugs in review sys

- client/src/components/LockIcon/LockIcon.tsx
- client/src/components/StepCard/StepCard.tsx
- client/src/components/StepCard/StepCardInteview.tsx
- client/src/components/StepCard/StepcardPayment.tsx
- client/src/data/staticData/admissionStages.ts
- client/src/pages/dashboard/index.tsx
- src/models/Portfolio.ts
1 - Refactored the step card ,to make the edge case handling better.
2 - Added links from interview step card to admission form
3 - Added cap to resubmission more than 3 times
> Dashboard Changes
